# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Docker Build Test

on:
  workflow_dispatch: null
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  issues: read
  pull-requests: read
  actions: write

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        include:
          - os: Linux
            platform: linux
            runs_on: ubuntu-latest
          - os: Windows
            platform: windows
            runs_on: windows-latest
          - os: MacOS
            platform: macos
            runs_on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build the image
        run: |
          docker buildx build -t hyperjump/monika:${{ matrix.platform }} .
